//TYPE
export const LOGIN = process.env.REACT_APP_LOGIN
export const SIGNUP = process.env.REACT_APP_SIGNUP
export const LOGOUT = process.env.REACT_APP_LOGOUT
export const NEW_TICKET = process.env.REACT_APP_NEW_TICKET
export const ALL_TICKETS = process.env.REACT_APP_ALL_TICKETS
export const LOGIN_ADMIN = process.env.REACT_APP_LOGIN_ADMIN
export const LOGOUT_ADMIN = process.env.REACT_APP_LOGOUT_ADMIN
export const EDIT_TICKET_ADMIN = process.env.REACT_APP_EDIT_TICKET_ADMIN
export const FILTER_TICKET_ADMIN = process.env.REACT_APP_FILTER_TICKET_ADMIN
export const ALL_TICKETS_ADMIN = process.env.REACT_APP_ALL_TICKETS_ADMIN
export const EDIT_TICKET = process.env.REACT_APP_EDIT_TICKET
export const DELETE_TICKET_ADMIN = process.env.REACT_APP_DELETE_TICKET_ADMIN
export const ALL_BUSINESS = process.env.REACT_APP_ALL_BUSINESS
export const DEPARTAMENT_BUSINESS = process.env.REACT_APP_DEPARTAMENT_BUSINESS
export const ALL_TECHNICALS = process.env.REACT_APP_ALL_TECHNICALS
export const ALL_USERS = process.env.REACT_APP_ALL_USERS
export const CREATE_TICKET_ADMIN = process.env.REACT_APP_CREATE_TICKET_ADMIN
export const ORDER_TICKETS = process.env.REACT_APP_ORDER_TICKETS
export const TICKET_ID = process.env.REACT_APP_TICKET_ID

//URL API
export const URL_LOGIN = process.env.REACT_APP_URL_LOGIN
export const URL_SIGNUP = process.env.REACT_APP_URL_SIGNUP
export const URL_NEWTICKET = process.env.REACT_APP_URL_NEWTICKET
export const URL_ALLTICKETS = process.env.REACT_APP_URL_ALLTICKETS
export const URL_LOGIN_ADMIN = process.env.REACT_APP_URL_LOGIN_ADMIN
export const URL_EDIT_TICKET_ADMIN = process.env.REACT_APP_URL_EDIT_TICKET_ADMIN
export const URL_FILTER_TICKET_ADMIN = process.env.REACT_APP_URL_FILTER_TICKET_ADMIN
export const URL_ALLTICKETS_ADMIN = process.env.REACT_APP_URL_ALLTICKETS_ADMIN
export const URL_EDIT_TICKET = process.env.REACT_APP_URL_EDIT_TICKET
export const URL_DELETE_TICKET_ADMIN = process.env.REACT_APP_URL_DELETE_TICKET_ADMIN
export const URL_ALL_BUSINESS = process.env.REACT_APP_URL_ALL_BUSINESS
export const URL_DEPARTAMENT_BUSINESS = process.env.REACT_APP_URL_DEPARTAMENT_BUSINESS
export const URL_ALL_TECHNICALS = process.env.REACT_APP_URL_ALL_TECHNICALS
export const URL_ALL_USERS = process.env.REACT_APP_URL_ALL_USERS
export const URL_CREATE_TICKET_ADMIN =process.env.REACT_APP_URL_CREATE_TICKET_ADMIN